### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by almmiko** [roya3000/react-router-dynamic-breadcrumbs#10]
Configure the project to use circleci and Travis CI

**Comment by ayyrickay** [comment]
Hey, I created a fork, but... To what purpose? I don't see a suite of unit tests. Are those in the work, or would creating the test infrastructure be a part of the PR?

**Comment by almmiko** [comment]
HI @ayyrickay, yes you right without tests this task useless. If you can create some unit tests it would be great.
