### ISSUE TITLE
Rendering root crumb

### ISSUE THREAD

**Issue by cvburgess** [roya3000/react-router-dynamic-breadcrumbs#3]
This library is fantastic and saved my team a ton of time.

Is there a way to display the root crumb by itself? ( '/' )
Currently it seems that if there is only one crumb the whole menu hides.

**Comment by almmiko** [comment]
Hi, thanks for using. Current version of this library does't show root itself('/). If you need to show '/' try to wrap breadcrumbs in your own component and simple check url and conditionally show components.

**Comment by octaharon** [comment]
@cvburgess If you need to display only a root breadcrumb you can do it like this
`<Route path="/" exact render={props=>(
  <a href='/'>Whatever</a>
)}/>`

If you mean that route breadcrumb is not displayed in a chain, I agree that this option needs more control, I will probably create a PR soon

**Comment by octaharon** [comment]
@cvburgess , @roya3000 see PR #4

**Comment by almmiko** [comment]
@octaharon, merged. Thank you for PR

**Comment by cvburgess** [comment]
Thank you @octaharon and @roya3000 - this is great work and appreciated!
