### ISSUE TITLE
How to set name on a specific breadcrumb items from props?

### ISSUE THREAD

**Issue by firmansyahrr** [roya3000/react-router-dynamic-breadcrumbs#5]
Hi, I have implemented this lib and this is really cool and easy to use but I got this question.. how to set the name on specific breadcrumb items from props ?..

For example : 

`/contact/:id/`

for the default breadcrumb will be show like this : 

`Contact > 6d3eb148-6a43-4824-aca8-613a4ac643ca`

when I set a const route and rename it to 

```
....
'/contact/:id': 'Detail',
....
```

which becomes

`Contact > Detail`

but how about if I want to set the breadcrumb name item with the contact name from props which i got from fetch data REST API ?

expected output

`Contact > Johnny Deep`

**Comment by almmiko** [comment]
Hello @firmansyahrr ! You can use a function instead of a string constant.
```
....
'/contact/:id': () => { //logic for getting a suitable route name }
....
```

**Comment by firmansyahrr** [comment]
Hi @roya3000 , 

thanks for the suggestion, i forgot to close this issue because i have solved this problem..

thanks a lot..

**Comment by javierGnz** [comment]
Hi @firmansyahrr

i have the same problem that you haved, can you explain to me how you resolved? maybe the solution is the same or at least to have a clue to solve that
