### ISSUE TITLE
placeholder matcher does not handle colons in url parameters

### ISSUE THREAD

**Issue by c3zi** [roya3000/react-router-dynamic-breadcrumbs#8]
In `BreadcrumbsItem.js` file we can see that you support only word characters and dash in url parameters:

`    const routeMatcher = new RegExp('^' + key.replace(placeholderMatcher, '([\\w-]+)') + '$');
`

A word character is a character from a-z, A-Z, 0-9, including the _ (underscore) character. I can imagine (this is my case) that someone has a colon in url parameters (like me). This pattern does not handle such situation. Could you modify your pattern and support colons and other allowed signs?

My proposal (very simple) is to change it like below or allow to pass the pattern from dedicated prop:

`    const routeMatcher = new RegExp('^' + key.replace(placeholderMatcher, '([\\w-:]+)') + '$');
`

**Comment by almmiko** [comment]
@c3zi Hello, thanks for reporting such use case. Feel free to make PR :)

**Comment by zhonghuiwen** [comment]
@roya3000 i've made a PR here https://github.com/roya3000/react-router-dynamic-breadcrumbs/pull/12

**Comment by zhonghuiwen** [comment]
I've made a PR here https://github.com/roya3000/react-router-dynamic-breadcrumbs/pull/13

**Comment by almmiko** [comment]
Hi @zhonghuiwen, Thank you for your PR!

**Comment by almmiko** [comment]
PR #13
